In [1]:
import pandas as pd

file_path = "/content/drive/MyDrive/Class Contents/5. Summer 2024/AI Lab/Class Materials For The Students/Week 7/simpleDatasetKMC.xlsx"

df = pd.read_excel(file_path)

print(df)

   X   Y
0  2  10
1  2   5
2  8   4
3  5   8
4  7   5
5  6   4
6  1   2
7  4   9


In [4]:
data_array = df.to_numpy()
data_array=data_array.astype(float)
print(data_array)

[[ 2. 10.]
 [ 2.  5.]
 [ 8.  4.]
 [ 5.  8.]
 [ 7.  5.]
 [ 6.  4.]
 [ 1.  2.]
 [ 4.  9.]]


In [13]:
import numpy as np
# let us create another table for normalized data
normalized_data=np.zeros_like(data_array)
#print(normalized_data)
print(normalized_data.shape)
noOfRows =normalized_data.shape[0]
noOfColumns =normalized_data.shape[1]

for i in range(noOfColumns):
    xmin=np.min(data_array[:,i])
    xmax=np.max(data_array[:,i])
    normalized_data[:,i]=(data_array[:,i]-xmin)/(xmax-xmin)
    #print(xmin)
    #print(xmax)
print(normalized_data)

(8, 2)
1.0
8.0
2.0
10.0
[[0.14285714 1.        ]
 [0.14285714 0.375     ]
 [1.         0.25      ]
 [0.57142857 0.75      ]
 [0.85714286 0.375     ]
 [0.71428571 0.25      ]
 [0.         0.        ]
 [0.42857143 0.875     ]]


In [26]:
k=3
noOfPoints = normalized_data.shape[0]
random_points = np.random.choice(noOfPoints,k,replace=False)
print(random_points)

centroids = normalized_data[random_points]
print(centroids)


[2 3 4]
[[1.         0.25      ]
 [0.57142857 0.75      ]
 [0.85714286 0.375     ]]


In [36]:
distances = np.zeros(shape=(noOfRows,k))
for i in range(k):
    distances[:,i] = np.sum( abs(normalized_data-centroids[i]),axis=1)

print(distances)

[[1.60714286 0.67857143 1.33928571]
 [0.98214286 0.80357143 0.71428571]
 [0.         0.92857143 0.26785714]
 [0.92857143 0.         0.66071429]
 [0.26785714 0.66071429 0.        ]
 [0.28571429 0.64285714 0.26785714]
 [1.25       1.32142857 1.23214286]
 [1.19642857 0.26785714 0.92857143]]


In [41]:
clusters = np.argmin(distances,axis=1)
print(clusters)

[1 2 0 1 2 2 2 1]


In [51]:
new_centroids = np.zeros_like(centroids)

for i in range(k):
    points = normalized_data[i==clusters]
    new_centroids[i]= points.mean(axis=0)

print(new_centroids)

[[1.         0.25      ]
 [0.38095238 0.875     ]
 [0.42857143 0.25      ]]
