In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
df = pd.read_excel("/content/drive/MyDrive/Colab Notebooks/logistic_regression_dataset.xlsx")
print(df)

     Feature_1  Feature_2  Feature_3  Output
0     0.496714  -0.138264   0.647689       1
1     1.523030  -0.234153  -0.234137       1
2     1.579213   0.767435  -0.469474       1
3     0.542560  -0.463418  -0.465730       1
4     0.241962  -1.913280  -1.724918       1
..         ...        ...        ...     ...
495   0.932591  -1.418366  -1.760809       1
496  -1.525656   1.262584  -0.551858       0
497   2.558199  -0.564248   0.184551       1
498   1.542110   2.006093   2.061504       1
499   1.208366   1.024063   0.592527       1

[500 rows x 4 columns]


In [3]:
dataset = df.to_numpy()
import numpy as np
# Create an empty array to store the normalized data
normalized_data = np.zeros_like(dataset)

# determine the number of columns
noOfColumns = dataset.shape[1]

# Normalize one column at a time using aloop
for i in range(noOfColumns):
    min_val = np.min(dataset[:, i])
    max_val = np.max(dataset[:, i])
    normalized_data[:, i] = (dataset[:, i] - min_val) / (max_val - min_val)


# print normalized data
print(normalized_data)
dataset=normalized_data

[[0.61961128 0.49096998 0.52172633 1.        ]
 [0.80703318 0.47579802 0.39013561 1.        ]
 [0.8172931  0.63427343 0.3550173  1.        ]
 ...
 [0.99607192 0.42356914 0.45261451 1.        ]
 [0.81051752 0.83025905 0.73270338 1.        ]
 [0.7495705  0.67487815 0.51349482 1.        ]]


In [4]:
X=dataset[:,0:3]
print(X)
Y=dataset[:,3]
print(Y.shape)
Y=Y.reshape(Y.shape[0],1)
print(Y.shape)
print(Y)

[[0.61961128 0.49096998 0.52172633]
 [0.80703318 0.47579802 0.39013561]
 [0.8172931  0.63427343 0.3550173 ]
 ...
 [0.99607192 0.42356914 0.45261451]
 [0.81051752 0.83025905 0.73270338]
 [0.7495705  0.67487815 0.51349482]]
(500,)
(500, 1)
[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]


In [5]:
# Sigmoid function
def sigmoid(z):
    return 1 / (1 + tf.exp(-z))

def lossFunction(yPred, yReal):
    n = yReal.shape[0]
    return -tf.reduce_mean(yReal * tf.math.log(yPred) + (1 - yReal) * tf.math.log(1 - yPred))


In [6]:
X_tensor = tf.Variable(X)
Y_tensor = tf.Variable(Y)

print(f'X_tensor shape = {X_tensor.shape}')
print(f'Y_tensor shape = {Y_tensor.shape}')

W_tensor = tf.Variable(np.random.randn(3, 1), dtype=tf.double)
print(f'W_tensor shape = {W_tensor.shape}')
b_tensor = tf.Variable(np.random.randn(1,1), dtype=tf.double)
print(f'b_tensor shape = {b_tensor.shape}')
learning_rate = 0.001
epochs=1000

X_tensor shape = (500, 3)
Y_tensor shape = (500, 1)
W_tensor shape = (3, 1)
b_tensor shape = (1, 1)


In [7]:
for i in range(epochs):
  with tf.GradientTape(persistent=True) as tape:
      Z = tf.matmul(X_tensor,W_tensor) + b_tensor
      YPred = sigmoid(Z)
      loss = lossFunction(YPred,Y_tensor)

  dlossBydW = tape.gradient(loss,W_tensor)
  dlossBydb = tape.gradient(loss,b_tensor)


  W_tensor.assign_sub(learning_rate*dlossBydW)
  b_tensor.assign_sub(learning_rate*dlossBydb)
  print(f"Epoch {i+1}, Loss: {loss.numpy()}")

print(W_tensor.numpy())
print(b_tensor.numpy())

Epoch 1, Loss: 0.6979448627237279
Epoch 2, Loss: 0.6979361361481634
Epoch 3, Loss: 0.6979274134851752
Epoch 4, Loss: 0.6979186947314554
Epoch 5, Loss: 0.6979099798836996
Epoch 6, Loss: 0.6979012689386056
Epoch 7, Loss: 0.6978925618928745
Epoch 8, Loss: 0.6978838587432098
Epoch 9, Loss: 0.6978751594863176
Epoch 10, Loss: 0.6978664641189071
Epoch 11, Loss: 0.6978577726376901
Epoch 12, Loss: 0.6978490850393814
Epoch 13, Loss: 0.6978404013206982
Epoch 14, Loss: 0.6978317214783607
Epoch 15, Loss: 0.6978230455090918
Epoch 16, Loss: 0.6978143734096168
Epoch 17, Loss: 0.6978057051766646
Epoch 18, Loss: 0.6977970408069661
Epoch 19, Loss: 0.697788380297255
Epoch 20, Loss: 0.6977797236442682
Epoch 21, Loss: 0.6977710708447449
Epoch 22, Loss: 0.697762421895427
Epoch 23, Loss: 0.6977537767930596
Epoch 24, Loss: 0.6977451355343901
Epoch 25, Loss: 0.6977364981161688
Epoch 26, Loss: 0.6977278645351488
Epoch 27, Loss: 0.6977192347880857
Epoch 28, Loss: 0.6977106088717381
Epoch 29, Loss: 0.6977019867828

In [8]:
X_test = X[-200:]
Y_test = Y[-200:]

# Predict Y using the learned weights and bias
Z_test = tf.matmul(X_test, W_tensor) + b_tensor
Y_pred_test = sigmoid(Z_test)
Y_pred_test = tf.round(Y_pred_test)  # Convert probabilities to 0 or 1

# Calculate performance metrics
TP = np.sum((Y_pred_test.numpy() == 1) & (Y_test == 1))
TN = np.sum((Y_pred_test.numpy() == 0) & (Y_test == 0))
FP = np.sum((Y_pred_test.numpy() == 1) & (Y_test == 0))
FN = np.sum((Y_pred_test.numpy() == 0) & (Y_test == 1))

# Accuracy
accuracy = (TP + TN) / (TP + TN + FP + FN)

# Precision
precision = TP / (TP + FP) if (TP + FP) != 0 else 0

# Recall
recall = TP / (TP + FN) if (TP + FN) != 0 else 0

# F1 Score
f1_score = 2 * (precision * recall) / (precision + recall) if (precision + recall) != 0 else 0

# Print metrics
print(f"Accuracy: {accuracy}")
print(f"Precision: {precision}")
print(f"Recall: {recall}")
print(f"F1 Score: {f1_score}")

Accuracy: 0.535
Precision: 0.631578947368421
Recall: 0.12244897959183673
F1 Score: 0.20512820512820512
