In [18]:
import numpy as np
import copy

In [19]:
class State:
    def __init__(self, board=None):
        if board is None:
            self.board = np.random.randint(0, 3, (6, 6))
        else:
            self.board = board
        self.h = 0
        self.parent = None
        self.choosenColor = None

    def printState(self):
        print("*******************")
        print(self.board)
        print("*******************")

    def flood_fill(self, target_color, replacement_color, r=0, c=0, visited=None):
        if visited is None:
            visited = np.zeros_like(self.board, dtype=bool)
        if r < 0 or r >= self.board.shape[0] or c < 0 or c >= self.board.shape[1]:
            return
        if visited[r][c] or self.board[r][c] != target_color:
            return

        visited[r][c] = True
        self.board[r][c] = replacement_color

        self.flood_fill(target_color, replacement_color, r+1, c, visited)
        self.flood_fill(target_color, replacement_color, r-1, c, visited)
        self.flood_fill(target_color, replacement_color, r, c+1, visited)
        self.flood_fill(target_color, replacement_color, r, c-1, visited)

    def applyColorChange(self, new_color):
        child = copy.deepcopy(self)
        target_color = child.board[0, 0]

        if target_color != new_color:
            child.flood_fill(target_color, new_color)

        return child

    def is_goal(self):
        return np.all(self.board == self.board[0, 0])

    def __eq__(self, other):
        return np.array_equal(self.board, other.board)

    def __hash__(self):
        return 1

In [20]:
def goalTest(node):
    return node.is_goal()

In [21]:
def heuristic_1(self):
    unique_colors, counts = np.unique(self.board, return_counts = True)
    most_frequent_color_count = np.max(counts)
    return self.board.size - most_frequent_color_count


def heuristic_2(node):
    target_color = node.board[0, 0]
    max_dist = 0
    for r in range(node.board.shape[0]):
        for c in range(node.board.shape[1]):
            if node.board[r][c] != target_color:
                max_dist = max(max_dist, r + c)  # Manhattan distance
    return max_dist

def calculateHeuristics(node):
    h1 = heuristic_1(node)
    h2 = heuristic_2(node)
    return (h1 + h2) * 2

In [22]:
def a_star_search(initialNode):
    if goalTest(initialNode):
        return initialNode

    frontier = list()
    explored = set()

    initialNode.h = calculateHeuristics(initialNode)
    frontier.append(initialNode)

    while frontier:
        frontier.sort(key=lambda x: x.h)
        node = frontier.pop(0)
        explored.add(node)

        if goalTest(node):
            return node

        for color in [0, 1, 2]:
            child = node.applyColorChange(color)
            if child not in frontier and child not in explored:
                child.h = calculateHeuristics(child)
                child.parent = node
                child.choosenColor = color
                if goalTest(child):
                    return child
                frontier.append(child)

    return None

In [23]:
def printSolution(final_state):
    if final_state is None:
      print("No solution found.")
      return

    path = []
    current = final_state
    while current:
        path.append(current)
        current = current.parent

    path.reverse()

    step_number = 0
    for state in path:
      print("Chosen Color: " + str(state.choosenColor))
      print(f"Step {step_number + 1}:")
      state.printState()
      step_number += 1

    if(step_number <= 5):
        print("\nYou Win")
    else:
        print("\nYou Lose. Try again...")



In [24]:
initial_state = State()
print("Initial Board:")
initial_state.printState()

result = a_star_search(initial_state)

print("Solution:")
printSolution(result)

Initial Board:
*******************
[[1 0 0 2 0 1]
 [0 1 2 2 2 2]
 [2 0 2 0 0 1]
 [1 2 1 1 2 0]
 [2 2 2 0 0 1]
 [0 1 1 0 2 2]]
*******************
Solution:
Chosen Color: None
Step 1:
*******************
[[1 0 0 2 0 1]
 [0 1 2 2 2 2]
 [2 0 2 0 0 1]
 [1 2 1 1 2 0]
 [2 2 2 0 0 1]
 [0 1 1 0 2 2]]
*******************
Chosen Color: 0
Step 2:
*******************
[[0 0 0 2 0 1]
 [0 1 2 2 2 2]
 [2 0 2 0 0 1]
 [1 2 1 1 2 0]
 [2 2 2 0 0 1]
 [0 1 1 0 2 2]]
*******************
Chosen Color: 2
Step 3:
*******************
[[2 2 2 2 0 1]
 [2 1 2 2 2 2]
 [2 0 2 0 0 1]
 [1 2 1 1 2 0]
 [2 2 2 0 0 1]
 [0 1 1 0 2 2]]
*******************
Chosen Color: 0
Step 4:
*******************
[[0 0 0 0 0 1]
 [0 1 0 0 0 0]
 [0 0 0 0 0 1]
 [1 2 1 1 2 0]
 [2 2 2 0 0 1]
 [0 1 1 0 2 2]]
*******************
Chosen Color: 1
Step 5:
*******************
[[1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 2 1 1 2 0]
 [2 2 2 0 0 1]
 [0 1 1 0 2 2]]
*******************
Chosen Color: 2
Step 6:
*******************
[[2 2 2 2 2 2]
 [2 2 2